// next
import type { NextPage } from 'next';
import Head from 'next/head';

// organisms
import { SpaceXPastLaunches } from '@organisms/index';

// templates
import { AppLayout } from '@templates/index';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Pabau Assignment | Fitim Bytyqi</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <AppLayout>
      <SpaceXPastLaunches />
    </AppLayout>
  </>
);

export default Home;
